### ISSUE TITLE
Clicking on the listview item app crashes

### ISSUE THREAD

**Issue by rajeevjaiswal** [Laimiux/RxTube#2]
Hi Laimiux,

I tried your sample code and videos does load in listview but when I click on any item app crashes

Caused by: java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.google.android.youtube.api.service.START }

 at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1722)
            at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1821)
            at android.app.ContextImpl.bindService(ContextImpl.java:1799)
            at android.content.ContextWrapper.bindService(ContextWrapper.java:545)
            at com.google.android.youtube.player.internal.r.e(Unknown Source)
            at com.google.android.youtube.player.YouTubePlayerView.a(Unknown Source)
            at com.google.android.youtube.player.YouTubeBaseActivity$a.a(Unknown Source)
            at com.google.android.youtube.player.YouTubePlayerView.initialize(Unknown Source)
            at com.laimiux.youtube.PlayerActivity.initializeVideo(PlayerActivity.java:51)
            at com.laimiux.youtube.PlayerActivity.onCreate(PlayerActivity.java:47)
            at android.app.Activity.performCreate(Activity.java:5990)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
            at android.app.ActivityThread.access$900(ActivityThread.java:154)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5292)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
11-14 14:14:06.249  28834-28848/com.laimiux.youtubeplayerexample W/art﹕ Suspending all threads took: 5.484ms
 Please tell me If I am doing anything wrong 
There is an updated version of  youtube player api 
https://developers.google.com/youtube/android/player/downloads/
The library needs to be updated?

**Comment by Laimiux** [comment]
Confirmed this is happening on my side as well. I looked into it and found the culprit
https://code.google.com/p/gdata-issues/issues/detail?id=6739

I've update the sample's targetSdkVersion to 19 for the time being. Now, it shouldn't crash

**Comment by Laimiux** [comment]
Actually, updated the Player library to 1.2.2, which completely fixed the issue without any necessary workarounds.

**Comment by rajeevjaiswal** [comment]
Thats why I added the player api 1.2.2 download link.

Thanks for quickly updating the library
